### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by jaruba** [ka2er/node-opensubtitles-api#2]
I'm getting:

    (node) warning: possible EventEmitter memory leak detected. 11 checksum-ready listeners added.
    Use emitter.setMaxListeners() to increase limit.

    os.computeHash - opensubtitles-api\lib\opensubtitles.js:49

If I run ```os.computeHash()``` multiple times.

**Comment by axelhzf** [comment]
Yes, it's leaking like hell. 500 executions leaks 130Mb.
