### ISSUE TITLE
Please check if your implementation works correctly

### ISSUE THREAD

**Issue by 2ge** [ka2er/node-opensubtitles-api#4]
Hi guys,

please check if your hashing code gives correct results. Now on OS is released correct JS code:

http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Javascript

**Comment by ka2er** [comment]
tested with dummy.bin and breakdance.avi and the hash computed are correct. Do you have another sample / test files that could be tested ? thks

**Comment by jaruba** [comment]
I think your implementation works correctly @ka2er , I tested it rigorously..

**Comment by 2ge** [comment]
When both files gives you correct result the implementation is correct. Thanks for looking at this.

**Comment by ka2er** [comment]
Verified so I close it. Please feel free to re open it if you find a test case that doesn't work (just point me to the file so I can reproduct it)
