### ISSUE TITLE
Possibility to release parts on MIT or LGPL?

### ISSUE THREAD

**Issue by vankasteelj** [ka2er/node-opensubtitles-api#6]
Hi,

I've used your functions checksumBuffer, sumHex, etc (hash computation) on my module (https://github.com/vankasteelj/opensubtitles-api), but I'd like to make it MIT for it to be 'possibly' used by 3rd party that can't use GPL. 

I'm not sure if what I'm asking is even possible, but could you release those functions (your name is listed on each: https://github.com/vankasteelj/opensubtitles-api/blob/master/lib/hash.js) with a little more 'permissive' license?

If not possible, or you don't want, no problem. But I thought it was worth asking :) 

thanks

**Comment by ka2er** [comment]
Hi,

I will ask people who contributed if they agree and if so, I will change my module licence to MIT. 

7 avril 2016 02:07 "Jean van Kasteel"  a écrit:
	Hi,

	I've used your functions checksumBuffer, sumHex, etc (hash computation) on my module (https://github.com/vankasteelj/opensubtitles-api (https://github.com/vankasteelj/opensubtitles-api)), but I'd like to make it MIT for it to be 'possibly' used by 3rd party that can't use GPL.

	I'm not sure if what I'm asking is even possible, but could you release those functions (your name is listed on each: https://github.com/vankasteelj/opensubtitles-api/blob/master/lib/hash.js (https://github.com/vankasteelj/opensubtitles-api/blob/master/lib/hash.js)) with a little more 'permissive' license?

	If not possible, or you don't want, no problem. But I thought it was worth asking :)

	thanks

**Comment by ka2er** [comment]
@AlexPoint @axelhzf Did you mind if the module change from GPL to MIT or LGPL ?

**Comment by axelhzf** [comment]
@ka2er I think MIT would be nice

**Comment by vankasteelj** [comment]
No reaction from @AlexPoint ?

**Comment by AlexPoint** [comment]
Sorry, I just completely forgot this thread.
Of course no problem switching to MIT license for me too!

**Comment by vankasteelj** [comment]
(btw, I was on npm looking for possible MIT alternatives aaaand... well, there's your code, everywhere, used in GPL, BSD and MIT code.)

**Comment by jaruba** [comment]
@vankasteelj 
![200_s](https://cloud.githubusercontent.com/assets/1777923/15094650/7c3d3f16-14b3-11e6-8497-74368f0e9877.gif)

:))

**Comment by vankasteelj** [comment]
s/st/b

**Comment by jaruba** [comment]
@vankasteelj the blonde on the left seems to approve of your string replace

**Comment by vankasteelj** [comment]
@ka2er when you have time to switch license then, thanks :)

**Comment by ka2er** [comment]
I will try before the next week.
If you are hurry don't hesitate to send me a PR with the licence switch.

**Comment by vankasteelj** [comment]
@ka2er done :)

**Comment by vankasteelj** [comment]
@ka2er I wanna release my 3.0 :D pretty please

**Comment by ka2er** [comment]
done. Sorry for the delay.

17 mai 2016 00:04 "Jean van Kasteel"  a écrit:
	@ka2er (https://github.com/ka2er) I wanna release my 3.0 :D pretty please

**Comment by vankasteelj** [comment]
awesome, thanks a lot!
